### PR TITLE
Upserts and prints and README

### PR DESCRIPTION
**Pull request by Anddraca**
# Changes
Some cleanup:

- DB updates now happen as upserts so the script can be run more than once without creating duplicates
- Added basic logging to show users activity
- Small edits to the README, happy to take suggestions

### CODE REVIEW

**Review by manivoxel51 — COMMENTED** [review]
Looking good! 💯 

One thought I had was to replace the `print` with a `log` and have the log_level as an environment variable which is off by default and on for migration script? this way we don't slow down the main api with logging extras.

**Comment by Anddraca** [comment]
> Looking good! 💯
> 
> One thought I had was to replace the `print` with a `log` and have the log_level as an environment variable which is off by default and on for migration script? this way we don't slow down the main api with logging extras.

Yeah, I had debated the print vs log for a while. Curious to hear others thoughts as well. Proper logging has lots of advantages, but also takes more overhead to set up and I didn't know if it was just overkill for this application. Ideally this is run once and then ignored. Worst case scenario it needs to run multiple times, or users need to diagnose why something isn't working.

I want to introduce a little more error handling for mid-run failures, but really the only things that go wrong here are network interruptions. We control the data we're retrieving, so there's a really low probability of something like corrupt data that would mess things up. Given that the realm of "something isn't working" is pretty small/precise I didn't go nuts with the logging.

I could be persuaded either way, that was just my thought process that got us to "eh, just use a bunch of prints"

**Review by j053y — COMMENTED** [review]
Eww generated files in a repo. Do we live in barn? :stuck_out_tongue: 

Two serious points though. 
1. I must have been out during the initial push. Why are we writing directly to Mongo and not using the CAS API? It already does all the writing to Mongo so we don't need to duplicate code. That's why we exposed a lot of those endpoints. 

2. I see the pattern of using Auth0 Management Factory. That's a pattern we used in the CAS and API because the tokens don't live longer than 24 and it expire. You shouldn't need this added complexity.

**Comment by Anddraca** [comment]
> Eww generated files in a repo. Do we live in barn? 😛

:angry: yeah I missed this in the gitignore in the initial commit. I'm moving out of the barn!

>I must have been out during the initial push. Why are we writing directly to Mongo and not using the CAS API? It already does all the writing to Mongo so we don't need to duplicate code. That's why we exposed a lot of those endpoints.

I had a similar discussion with Ritchie -- I did it this way so that it would be executed without needing a CAS already stood up, but also stated that I don't have a strong opinion on that. I will submit another PR to use the CAS API instead. It's just a question of what workflow we want to require from customers

> I see the pattern of using Auth0 Management Factory. That's a pattern we used in the CAS and API because the tokens don't live longer than 24 and it expire. You shouldn't need this added complexity.

Yep, this was mostly a copy pasta intentionally done to save time. Goal was to get the benefits of the work we've done in the API without needing to rewrite things. This can be cleaned up. I don't think it's introducing some noticeable overhead, but agree that it's just unnecessary code for the purposes of this.

**Comment by j053y** [comment]
> I had a similar discussion with Ritchie -- I did it this way so that it would be executed without needing a CAS already stood up, but also stated that I don't have a strong opinion on that. I will submit another PR to use the CAS API instead. It's just a question of what workflow we want to require from customers

That makes some sense. I guess would assume they already have a CAS setup as this is migrating from one mode to the other. Directly to mongo makes sense if we weren't putting everyone on CAS first, which to my knowledge we are doing.

**Comment by Anddraca** [comment]
>That makes some sense. I guess would assume they already have a CAS setup as this is migrating from one mode to the other. Directly to mongo makes sense if we weren't putting everyone on CAS first, which to my knowledge we are doing.

yep, basically there were two paths to me: you have CAS or you don't. I chose the path where the user doesn't but just cause it sounded reasonable to me :D I'll submit a PR where this hits CAS instead of mongo and see what it looks like. There also could be a world where both implementations sit there and are chosen by configuration

**Comment by Anddraca** [comment]
Closing this PR in favor of https://github.com/voxel51/fiftyone-auth-migration/pull/2

**Pull request closed without merging**
